=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- /<category>/curves.xml -->

    <xs:element name="id" type="xs:string"/>
    <xs:element name="desc" type="xs:string"/>
    <xs:element name="bits" type="xs:positiveInteger"/>
    <xs:element name="field">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="prime"/>
                <xs:enumeration value="binary"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="file" type="xs:string"/>

    <xs:element name="curve">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="desc" minOccurs="0"/>
                <xs:element ref="bits"/>
                <xs:element ref="field"/>
                <xs:element ref="file"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="curves">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="curve" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- /<category>/keys.xml -->

    <xs:element name="privkey">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id" />
                <xs:element ref="file"/>
                <xs:element name="curve" type="xs:string"/>
                <xs:element ref="desc" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pubkey">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id" />
                <xs:element ref="file"/>
                <xs:element name="curve" type="xs:string"/>
                <xs:element ref="desc" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="keypair">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id" />
                <xs:element ref="file"/>
                <xs:element name="curve" type="xs:string"/>
                <xs:element ref="desc" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="keys">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="keypair" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="privkey" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="pubkey" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string"/>
            <xs:attribute name="desc" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- /categories.xml -->

    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="directory" type="xs:string"/>
                <xs:element name="desc" minOccurs="0" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="category" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/smallpub/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>ecsp128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>ecsp128.csv</file>
    </curve>
    <curve>
        <id>ecsp160</id>
        <bits>160</bits>
        <field>prime</field>
        <file>ecsp160.csv</file>
    </curve>
    <curve>
        <id>ecsp192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>ecsp192.csv</file>
    </curve>
    <curve>
        <id>ecsp224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>ecsp224.csv</file>
    </curve>
    <curve>
        <id>ecsp256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>ecsp256.csv</file>
    </curve>
    <curve>
        <id>ecsp384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>ecsp384.csv</file>
    </curve>
    <curve>
        <id>ecsp521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>ecsp521.csv</file>
    </curve>
</curves>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/anomalous/curves.xml
<?xml version="1.0" encoding="UTF-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
	<curve>
		<id>miyaji128a1</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128a1.csv</file>
		<desc>First curve in the "Proposed scheme A" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>miyaji128a2</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128a2.csv</file>
		<desc>Second curve in the "Proposed scheme A" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>miyaji128b1</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128b1.csv</file>
		<desc>First curve in the "Proposed scheme B" section of Atsuko Miyaji's paper.</desc>
	</curve>
	<curve>
		<id>miyaji128b2</id>
		<bits>128</bits>
		<field>prime</field>
		<file>miyaji128b2.csv</file>
		<desc>Second curve in the "Proposed scheme B" section of Atsuko Miyaji's paper.</desc>
	</curve>
</curves>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/categories.xml
<?xml version="1.0" encoding="UTF-8" ?>
<categories xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="schema.xsd">
    <category>
        <name>anomalous</name>
        <directory>anomalous</directory>
        <desc>These prime field curves have the same order as the field order, and are susceptible to attacks reducing ECDLP over a multiplicative group of the curve, to DLP over an additive group of the underlying field, which is easy (linear time).</desc>
    </category>
    <category>
        <name>brainpool</name>
        <directory>brainpool</directory>
        <desc>ECC Brainpool Standard Curves and Curve Generation v. 1.0  19.10.2005</desc>
    </category>
    <category>
        <name>nist</name>
        <directory>nist</directory>
        <desc>RECOMMENDED ELLIPTIC CURVES FOR FEDERAL GOVERNMENT USE  July 1999</desc>
    </category>
    <category>
        <name>secg</name>
        <directory>secg</directory>
        <desc>SEC 2: Recommended Elliptic Curve Domain Parameters version 2.0  January 27, 2010</desc>
    </category>
    <category>
        <name>nonprime</name>
        <directory>nonprime</directory>
        <desc>Non-prime order curves, with points of very small order pregenerated.</desc>
    </category>
    <category>
        <name>wrong</name>
        <directory>wrong</directory>
        <desc>Wrong field curves. These should definitely give an error when used. Since the "prime" used for the field are not prime, and the field polynomials are also not irreducible. Simply put these parameters don't specify a valid elliptic curve.</desc>
    </category>
    <category>
        <name>invalid</name>
        <directory>invalid</directory>
        <desc></desc>
    </category>
    <category>
        <name>test</name>
        <directory>test</directory>
        <desc>Test vectors</desc>
    </category>
</categories>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/cofactor/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">

    <curve>
        <id>cofactor2p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor2p128.csv</file>
    </curve>
    <curve>
        <id>cofactor4p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor4p128.csv</file>
    </curve>
    <curve>
        <id>cofactor8p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor8p128.csv</file>
    </curve>
    <curve>
        <id>cofactor16p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor16p128.csv</file>
    </curve>
    <curve>
        <id>cofactor32p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor32p128.csv</file>
    </curve>
    <curve>
        <id>cofactor64p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor64p128.csv</file>
    </curve>
    <curve>
        <id>cofactor128p128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>cofactor128p128.csv</file>
    </curve>
</curves>
