=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <!-- /<category>/curves.xml -->

    <xs:element name="id" type="xs:string"/>
    <xs:element name="desc" type="xs:string"/>
    <xs:element name="bits" type="xs:positiveInteger"/>
    <xs:element name="field">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="prime"/>
                <xs:enumeration value="binary"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="file" type="xs:string"/>

    <xs:element name="curve">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id"/>
                <xs:element ref="desc" minOccurs="0"/>
                <xs:element ref="bits"/>
                <xs:element ref="field"/>
                <xs:element ref="file"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="curves">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="curve" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- /<category>/keys.xml -->

    <xs:element name="privkey">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id" />
                <xs:element ref="file"/>
                <xs:element name="curve" type="xs:string"/>
                <xs:element ref="desc" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="pubkey">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id" />
                <xs:element ref="file"/>
                <xs:element name="curve" type="xs:string"/>
                <xs:element ref="desc" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="keypair">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="id" />
                <xs:element ref="file"/>
                <xs:element name="curve" type="xs:string"/>
                <xs:element ref="desc" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="keys">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="keypair" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="privkey" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="pubkey" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string"/>
            <xs:attribute name="desc" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <!-- /categories.xml -->

    <xs:element name="category">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="directory" type="xs:string"/>
                <xs:element name="desc" minOccurs="0" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="categories">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="category" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/composite/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd"
      category="composite"
      desc="Points on the non-prime curves, very small point orders(3-5).">
    <pubkey>
        <id>composite128-pub</id>
        <file>composite128_pub.csv</file>
        <curve>composite/composite128</curve>
        <desc>order = 5</desc>
    </pubkey>
    <pubkey>
        <id>composite160-pub</id>
        <file>composite160_pub.csv</file>
        <curve>composite/composite160</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>composite192-pub</id>
        <file>composite192_pub.csv</file>
        <curve>composite/composite192</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>composite224-pub</id>
        <file>composite224_pub.csv</file>
        <curve>composite/composite224</curve>
        <desc>order = 5</desc>
    </pubkey>
    <pubkey>
        <id>composite256-pub</id>
        <file>composite256_pub.csv</file>
        <curve>composite/composite256</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>composite384-pub</id>
        <file>composite384_pub.csv</file>
        <curve>composite/composite384</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>composite521-pub</id>
        <file>composite521_pub.csv</file>
        <curve>composite/composite521</curve>
        <desc>order = 5</desc>
    </pubkey>
</keys>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/nonprime/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>nonprime128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>nonprime128.csv</file>
    </curve>
    <curve>
        <id>nonprime160</id>
        <bits>160</bits>
        <field>prime</field>
        <file>nonprime160.csv</file>
    </curve>
    <curve>
        <id>nonprime192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>nonprime192.csv</file>
    </curve>
    <curve>
        <id>nonprime224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>nonprime224.csv</file>
    </curve>
    <curve>
        <id>nonprime256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>nonprime256.csv</file>
    </curve>
    <curve>
        <id>nonprime384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>nonprime384.csv</file>
    </curve>
    <curve>
        <id>nonprime521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>nonprime521.csv</file>
    </curve>
</curves>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/test/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd"
      category="test"
      desc="Test vectors">
    <keypair>
        <id>secp160r1-U</id>
        <file>secg/secp160r1-keyU.csv</file>
        <curve>secg/secp160r1</curve>
    </keypair>
    <keypair>
        <id>secp160r1-V</id>
        <file>secg/secp160r1-keyV.csv</file>
        <curve>secg/secp160r1</curve>
    </keypair>
</keys>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/cofactor/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE keys [
	<!ENTITY secg SYSTEM "cofactor/secg_keys.xml">
	]>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd"
      category="cofactor"
      desc="">

    <pubkey>
        <id>cofactor2p128/0</id>
        <inline>0x1274cf343b12c9de044a312c7e0d88b1,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor2p128</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor4p128/0</id>
        <inline>0x4e5a1eb60f6d2cb5c24f6ea54a675cd6,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor4p128</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor8p128/0</id>
        <inline>0x31eb5f732057b0ea57eed55f4259d85d,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor8p128</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor16p128/0</id>
        <inline>0x89578c4527e2d5e8a95905e30f0889e3,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor16p128</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor32p128/0</id>
        <inline>0x097191ee5ded1c36f2ec6bba78e7e6ea,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor32p128</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor64p128/0</id>
        <inline>0x1d360b7f2f805be59aedeaae2813ee1f,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor64p128</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor128p128/0</id>
        <inline>0x485b34188824c54f115f31891c18795c,0x00000000000000000000000000000000</inline>
        <curve>cofactor/cofactor128p128</curve>
        <desc>order = 2</desc>
    </pubkey>

    <pubkey>
        <id>cofactor2t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x0132720c6aa3f2ca65d18f2de81e5e6b8ad4a3ef9d</inline>
        <curve>cofactor/cofactor2t163</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor4t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x00b93d46bc80b487e7738644e85bb6d29c2dca2600</inline>
        <curve>cofactor/cofactor4t163</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor8t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x0569879d9674b06578f62ec2f341ddd3b648dfdf51</inline>
        <curve>cofactor/cofactor8t163</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor16t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x04274cf55c49c32ca4c0e30b891e03b3b1c6597df0</inline>
        <curve>cofactor/cofactor16t163</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor32t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x0409969efb468e8f07954a3b4bf7610a0d8b5d4753</inline>
        <curve>cofactor/cofactor32t163</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor64t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x068c5445c03a59d697573b09ae0804e2891bb98208</inline>
        <curve>cofactor/cofactor64t163</curve>
        <desc>order = 2</desc>
    </pubkey>
    <pubkey>
        <id>cofactor128t163/0</id>
        <inline>0x000000000000000000000000000000000000000000,0x06be374502a948489de2e7d8d82cb6b62a493b77a0</inline>
        <curve>cofactor/cofactor128t163</curve>
        <desc>order = 2</desc>
    </pubkey>

    &secg;
</keys>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/nist/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>P-192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>p192.csv</file>
    </curve>
    <curve>
        <id>P-224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>p224.csv</file>
    </curve>
    <curve>
        <id>P-256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>p256.csv</file>
    </curve>
    <curve>
        <id>P-384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>p384.csv</file>
    </curve>
    <curve>
        <id>P-521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>p521.csv</file>
    </curve>
</curves>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/smallpub/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<keys xmlns="http://crcs.cz/ectester/curves"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://crcs.cz/ectester/curves ../schema.xsd"
      category="smallpub"
      desc="Points on the Non-prime smallpub curves, very small point orders(3-5).">
    <pubkey>
        <file>ecsp128_pub.csv</file>
        <curve>ecsp128</curve>
    </pubkey>
    <pubkey>
        <file>ecsp160_pub.csv</file>
        <curve>ecsp160</curve>
    </pubkey>
    <pubkey>
        <file>ecsp192_pub.csv</file>
        <curve>ecsp192</curve>
    </pubkey>
    <pubkey>
        <file>ecsp224_pub.csv</file>
        <curve>ecsp224</curve>
    </pubkey>
    <pubkey>
        <file>ecsp256_pub.csv</file>
        <curve>ecsp256</curve>
    </pubkey>
    <pubkey>
        <file>ecsp384_pub.csv</file>
        <curve>ecsp384</curve>
    </pubkey>
    <pubkey>
        <file>ecsp521_pub.csv</file>
        <curve>ecsp521</curve>
    </pubkey>
</keys>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/composite/curves.xml
<?xml version="1.0" encoding="utf-8" ?>
<curves xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schema.xsd">
    <curve>
        <id>whole/composite128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>composite128.csv</file>
        <desc>r = order = 0x03 * 0x05 * 0x3b * 0x3a107e02cd073c8e24bf55730f1733</desc>
    </curve>
    <curve>
        <id>whole/composite160</id>
        <bits>160</bits>
        <field>prime</field>
        <file>composite160.csv</file>
        <desc>r = order = 0x02 * 0x03 * 0x6b * 0x1ee99b75143833bbc11d409601c25f9566a001</desc>
    </curve>
    <curve>
        <id>whole/composite192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>composite192.csv</file>
        <desc>r = order = 0x02 * 0x03 * 0x05 * 0x13 * 0x19bc3c00e2a7ad9e40d12e5d9e29a2b5ce80b3a3e84295</desc>
    </curve>
    <curve>
        <id>whole/composite224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>composite224.csv</file>
        <desc>r = order = 0x02 * 0x03 * 0x1d * 0x1538e6a6dc906d724a7bf51c77bce9d46865bd92d8bca01f887405</desc>
    </curve>
    <curve>
        <id>whole/composite256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>composite256.csv</file>
        <desc>r = order = 0x02 * 0x05 * 0x11 * 0x1382cadcdd2b90b90b81eda82433bf574b5d8f5654dcc62341c7e967f2e811</desc>
    </curve>
    <curve>
        <id>whole/composite384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>composite384.csv</file>
        <desc>r = order = 0x05 * 0x0b * 0x3d * 0xb16aa7dc50145337cf1b2f38018ccb5cf44c22a2f7d7c22bbe5c572d2cb9a04cb1081357c6a1c97cc39ab62596867</desc>
    </curve>
    <curve>
        <id>whole/composite521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>composite521.csv</file>
        <desc>r = order = 0x02 * 0x05 * 0x1f * 0x4a5aac4fac3ea253b66c3e650f5173b30467f28b8e841d37ce69bb0831a5939ad3dd082b750577ec4592d4d58916c87a9b732d8ddae435c26f8f779d2467f50f</desc>
    </curve>

    <curve>
        <id>small/composite128</id>
        <bits>128</bits>
        <field>prime</field>
        <file>composite128_small.csv</file>
        <desc>r = 0x03</desc>
    </curve>
    <curve>
        <id>small/composite160</id>
        <bits>160</bits>
        <field>prime</field>
        <file>composite160_small.csv</file>
        <desc>r = 0x03</desc>
    </curve>
    <curve>
        <id>small/composite192</id>
        <bits>192</bits>
        <field>prime</field>
        <file>composite192_small.csv</file>
        <desc>r = 0x03</desc>
    </curve>
    <curve>
        <id>small/composite224</id>
        <bits>224</bits>
        <field>prime</field>
        <file>composite224_small.csv</file>
        <desc>r = 0x03</desc>
    </curve>
    <curve>
        <id>small/composite256</id>
        <bits>256</bits>
        <field>prime</field>
        <file>composite256_small.csv</file>
        <desc>r = 0x05</desc>
    </curve>
    <curve>
        <id>small/composite384</id>
        <bits>384</bits>
        <field>prime</field>
        <file>composite384_small.csv</file>
        <desc>r = 0x05</desc>
    </curve>
    <curve>
        <id>small/composite521</id>
        <bits>521</bits>
        <field>prime</field>
        <file>composite521_small.csv</file>
        <desc>r = 0x05</desc>
    </curve>
</curves>

=== DalavanCloud/ECTester/src/cz/crcs/ectester/data/nonprime/keys.xml
<?xml version="1.0" encoding="utf-8" ?>
<keys xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="../schema.xsd"
      category="nonprime"
      desc="Points on the non-prime curves, very small point orders(3-5).">
    <pubkey>
        <id>nonprime128-pub</id>
        <file>nonprime128_pub.csv</file>
        <curve>nonprime/nonprime128</curve>
        <desc>order = 5</desc>
    </pubkey>
    <pubkey>
        <id>nonprime160-pub</id>
        <file>nonprime160_pub.csv</file>
        <curve>nonprime/nonprime160</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>nonprime192-pub</id>
        <file>nonprime192_pub.csv</file>
        <curve>nonprime/nonprime192</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>nonprime224-pub</id>
        <file>nonprime224_pub.csv</file>
        <curve>nonprime/nonprime224</curve>
        <desc>order = 5</desc>
    </pubkey>
    <pubkey>
        <id>nonprime256-pub</id>
        <file>nonprime256_pub.csv</file>
        <curve>nonprime/nonprime256</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>nonprime384-pub</id>
        <file>nonprime384_pub.csv</file>
        <curve>nonprime/nonprime384</curve>
        <desc>order = 3</desc>
    </pubkey>
    <pubkey>
        <id>nonprime521-pub</id>
        <file>nonprime521_pub.csv</file>
        <curve>nonprime/nonprime521</curve>
        <desc>order = 5</desc>
    </pubkey>
</keys>
